### ISSUE TITLE
Umbrella issue for v1.0.0

### ISSUE THREAD

**Issue by Khaledgarbaya** [axios/axios#1333]
## Summary
This issue is an umbrella for the next release of axios. We might add more issues to the `issues to fix` list. 

## Pull Requests
* [x] [Babel & Webpack 3](https://github.com/axios/axios/pull/1334)
* [x] [ESLint shared config (standard)](https://github.com/axios/axios/pull/1335)
* [x]  [Migrate nodeunit to jasmine](https://github.com/axios/axios/pull/1336)
* [x] [Karma with Webpack config](https://github.com/axios/axios/pull/1339)
* [x] [Adjust specs to work with new lib interface](https://github.com/axios/axios/pull/1351)
* [x] [Substitute custom utils with lodash](https://github.com/axios/axios/pull/1352)
* [ ] Move core / adapters to ESM
* [ ] Move helpers to ESM
* [ ] Remove lodash helpers from utils
* [ ] Move cancel module to ESM
* [ ] Change external surface

### Build system

- [x] https://github.com/axios/axios/issues/1209
- [x] https://github.com/axios/axios/issues/1259

### Utils:

- [x] https://github.com/axios/axios/issues/1298

### Default instances / Config merge:

- [x] https://github.com/axios/axios/pull/533
- [x] https://github.com/axios/axios/issues/1239 - closed in favor of #385
- [ ] https://github.com/axios/axios/issues/1237
- [ ] https://github.com/axios/axios/issues/812
- [ ] https://github.com/axios/axios/issues/369
- [ ] https://github.com/axios/axios/issues/723
- [ ] maybe https://github.com/axios/axios/issues/498
- [ ] https://github.com/axios/axios/issues/385
- [ ] https://github.com/axios/axios/issues/382
- [ ] maybe https://github.com/axios/axios/issues/370
- [ ] https://github.com/axios/axios/issues/369
- [ ] https://github.com/axios/axios/issues/809
- [ ] https://github.com/axios/axios/issues/688
- [ ] https://github.com/axios/axios/issues/587
- [ ] https://github.com/axios/axios/issues/1042

### Proxy:

- [ ] https://github.com/axios/axios/issues/434
- [ ] https://github.com/axios/axios/issues/1243
- [ ] https://github.com/axios/axios/issues/636

### Default adapter / Weird aliasing:

- [ ] https://github.com/axios/axios/issues/1284

### Fixed due to old IE support removal:

- [ ] https://github.com/axios/axios/issues/807
- [ ] https://github.com/axios/axios/issues/764

### Parse response based on `responseType`

- [ ] https://github.com/axios/axios/issues/811 (links 5 other issues with similar problem)
- [ ] https://github.com/axios/axios/issues/793
- [ ] https://github.com/axios/axios/issues/765
- [ ] https://github.com/axios/axios/issues/724

## After branches have been merged

* [ ] last verification of code integrety / bugfixes
* [ ] proper CHANGELOG.md
* [ ] migration hints in README.md
* [ ] Setup coverage via CodeCov
* [ ] Investigate necessity of banner usage (could be solved via `BannerPlugin`)
* [ ] Add a NPM script for running the TypeScript test
* [ ] Remove Bower distribution
* [ ] Documentation #257

## When alpha has been released

* [ ] mention potentially fixed issues to get some usage

**Comment by axe312ger** [comment]
as soon #1334 reaches master, we would close #1209

@Khaledgarbaya maybe add it to the umbrella including a [x] :)

**Comment by Khaledgarbaya** [comment]
Closing will happen later when we have the alpha release

**Comment by mividtim** [comment]
Also consider https://github.com/axios/axios/issues/1286 please (a PR is available here: https://github.com/axios/axios/pull/1287). Any idea on time-frame?

**Comment by zcei** [comment]
@mividtim those three lines should still be merge-able afterwards, the HTTP adapter won't change much.

For a timeline, there's nothing specific, but we have everything mentioned in `Pull Requests` ready. The branches will be updated one-by-one to the latest of `release/1.0.0` when I open them as PRs. Then it's mainly about reviews - and for the last one (`Change external surface`) I expect some discussions (but the overall direction was discussed with Matt already).

After that, we should give people some time trying the alpha, which will be the most blocking part time-wise I guess.

**Comment by emilyemorehouse** [comment]
Do we have a way of tracking deprecations/breaking changes for 1.0.0?

**Comment by Khaledgarbaya** [comment]
@emilyemorehouse we'll add a `CHANGELOG` soon to the `release/1.0.0` branch. @zcei has already something in place in his machine

**Comment by emilyemorehouse** [comment]
@Khaledgarbaya perfect. Wanted to make sure #1042 / #1234 can be tracked and deprecated properly. Thanks!

**Comment by zcei** [comment]
Ah there are even issues for that - thanks for pointing out. @Khaledgarbaya can add them to the list of issues.

**Comment by jcrben** [comment]
Can we agree that no (or extremely limited) breaking changes will be made in 1.0 and instead only deprecation warnings will be added? Then the code can be removed in 2.0.

This is how both Ember.js and React typically handle deprecations / removals.

**Comment by zcei** [comment]
As noted in the readme & how SemVer works, we could do a 0.18 with the deprecations, once we have a quite stable alpha for 1.0, and know exactly which implications will happen.
I personally don't see the value in losing the "symbolic act" of a `v1.0` to only add deprecations.

Everything that we're planning to get rid of can be achieved today, expect for a more deterministic global config (no mutation, changed defaults don't propagate to already created instances). 

Any idea how we could track that people use defaults that have been added after an instance has been created? Then we could trigger a deprecation warning only for these use-cases.

**Comment by jcrben** [comment]
The 0 major version rule for semver catches some people off-guards, but 0.18 sounds OK - I'm just hoping can run the new stuff and the old stuff at the same time for a version. Then introducing deprecations along the way in 1.0 and removed in 2.0...

As far as tracking assignment to global defaults (https://github.com/axios/axios/tree/14057dc0bd9811a9fda773588f66de9f4aa0f617#global-axios-defaults), maybe a setter with `defineProperty()` or a [proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy)?

**Comment by mividtim** [comment]
@jcrben @zcei I've run into a similar situation in a separate, logging project before (global configuration that can be updated at runtime), and discovered this pattern, which may be useful to you: https://stackoverflow.com/questions/40271823/es6-emitting-events-from-static-methods

Basically, new up a `private static emitter = new EventEmitter()` on the class, and all instances can then listen for it: `AxiosInstance.emitter.on('configChanged')` or something similar. The risk here, of course, is cleanup. If all instances have a reference to a static event emitter, and the emitter never loses scope, none of the instances will ever be cleaned up. It's a conundrum.

**Comment by darren128** [comment]
@zcei  [#1298](https://github.com/axios/axios/issues/1298) looks like it's checked off, but the utils aren't actually being exported from the module. Is this in the plans?

**Comment by emilyemorehouse** [comment]
@darren128 is this what you're looking for? check out the current utils, there are methods exported: https://github.com/axios/axios/blob/release/1.0.0/lib/utils.js

**Comment by zcei** [comment]
The module doesn't re-export the utils, you'd need to require/import into the actual files. We can think about a top-level file that re-exports them, so you don't need to tap into `dist`.

Wondering whether the use-case of #1298 could be solved with interceptors or adding another request/response transformer. The config accepts an array, so you can utilize the default and your custom processing on top.

**Comment by darren128** [comment]
We decided to use the interceptor to solve the issue outlined in #1298. But we are now using a copy / pasted version of the is* utils to determine what to / not to batch. For example, we are not batching file uploads. We just need to determine this before we send the batch off to axios, thus why an interceptor doesn't work for this case.

**Comment by danieladams456** [comment]
Would #959 be close enough for the 1.0.0 release?  It would help when developing within a corporate network.

**Comment by mjhenkes** [comment]
Just checking in, Are there still plans to release a 1.0.0 of axios?

**Comment by axe312ger** [comment]
Alright, after working on this 2 years ago and the situation overall not changing:

I drop out of working further on axios.

This lib is mostly needed for enterprises to get requests running through their in-house proxies or support very old browsers. (At least that was my experience when maintaining libs depending on axios)

These companies should take over and/or pay further development of axios. The whole issue queue is packed with people complaining instead of fixing, or forking and rereleasing. This is open source, if you need it so much, take the time, the money or find smb doing it for u.

Everybody else not needing the exotic axios features, might just go with node-fetch, fetch and all the other, way less monolithic and smaller options to do a HTTP request in 2019

Over and out 🙇

**Comment by axe312ger** [comment]
Even unstarred the repo. Hopefully never bloating my projects with it 😁 

Wtf there are `1,485,321` projects using this and nobody feels responsible or the real need to fix this 😅

**Comment by ThiefMaster** [comment]
@axe312ger you sound a bit salty... reasons to not use fetch directly:

- no nice api to turn an object into a query string
- no interceptors (very convenient to make the user login again and then just continue whatever request failed due to an expired session)
- nicer API (getting json quickly without two awaits)

**Comment by schmod** [comment]
More conversation over in #2265.  

If we aren't making any traction with these major changes, let's just bump our current version to 1.0.0, and release these changes as a 2.x branch when they're ready.  The 0.18 branch is one of the most heavily-used and well-tested pieces of software in the JavaScript ecosystem.  A lack of activity isn't necessarily a bad thing -- it means stability!  Let's just formalize the status-quo and slap the 1.0.0 designation onto the current release.

**Comment by 43081j** [comment]
Just came across this randomly so here's an opinion:

This issue is 2 years old almost, you have almost certainly reached the dangling-branch/tech debt point where you should throw this away and do a better, more modern v1. Things have changed since you opened this.

For example, since you made your now-dated v1 branch, all browsers and node support ESM. you have no reason to be still writing commonjs for what is aimed at browsers. Your branch is so old it is only going to hold you back from modernising your already aged codebase.

IMO you should accept the loss, drop your dangling branch, make a new v1 in ESM and have a rollup (tree-shaking enabled) bundle for older browsers (all those enterprise users using axios).

Similarly, a move to lodash seems like a step backwards. Most of what you're pulling out of lodash exists in the platform now or is at most one line of extra code (you even pull in a `trim`...)

**Comment by jasonsaayman** [comment]
HI all, thanks for the work done on here but for now I am going to close this issue. I think that we first need to gain stability in Axios and a V1 is probably a bit away and I am hoping would be a overall of parts of the API and code base and include modernisation. 

Thank you everyone that was involved here but for now I am going to close this and will open a new project for a V1 as soon as possible.
