### ISSUE TITLE
Planning for 1.0

### ISSUE THREAD

**Issue by mzabriskie** [axios/axios#206]
This library has been around for about a year and a half and has seen good adoption. In order to release a 1.0 version, a library should come with a high level of confidence in it's reliability as well as provide a stable API for the features that are needed for most use cases.

In planning for a 1.0 release there are a few features that need to be implemented. If you have something you feel should be included in a 1.0 release please link to an issue (new or existing) in the comments below. If I agree I will add it to the checklist here. Once the checklist is defined I will work on getting items completed. Any help during this process would be greatly appreciated!
- [ ] Documentation #257
- [x] Cancel request #50
- [x] Support `$http_proxy` #107
- [x] Define HTTP status code error range #41
- [x] Support `onprogress` #82
- [x] Reject with `Error` #306
- [x] Cookies for Node #48
- [x] Cache `GET` responses #31

**Comment by FarhadG** [comment]
Thanks for the update, @mzabriskie. I'd love to help with the caching feature. Are you planning to use a module for this functionality or build one?

**Comment by mzabriskie** [comment]
@FarhadG I built a [module](https://github.com/mzabriskie/felix) for caching that I had considered using for this, but I am not married to that. It would be nice to allow whatever is used to be pluggable, so people can provide their own cache mechanism if they want.

**Comment by dmt0** [comment]
Any plan for more releases before 1.0?

**Comment by mzabriskie** [comment]
@dmt0 yes, I am working on a release right now (0.10.0) and will continue to release patches to fix issues. 1.0.0 is the next major milestone that I am pushing towards.

**Comment by adrianhyde** [comment]
Hi @mzabriskie do you know when 0.9.2 or 0.10.0 will be released. Looking to use fix #227 
Thanks

**Comment by amitthakkar22288** [comment]
+1 for 0.10.0. Looking forward to see this on npm soon. Thanks for this awesome library.

**Comment by bboysathish** [comment]
Hi @mzabriskie Me too Looking for fix https://github.com/mzabriskie/axios/pull/227

**Comment by adampickeral** [comment]
also looking for the #227 fix

**Comment by mzabriskie** [comment]
For those looking for a fix to #227 it is available in version 0.10.0

**Comment by bboysathish** [comment]
Thanks @mzabriskie .. Waiting for it long time.. Nice work.. !!

**Comment by MMeent** [comment]
I would like to use this as an include in my ES6 project, so #181 is something I'd like to see.

**Comment by mzabriskie** [comment]
@MMeent you should be fine to include axios into an ES6 module as is. Are you getting an error?

**Comment by MMeent** [comment]
@mzabriskie I cannot seem to find the place of the ES6 module. My file structure is axios/dist/axios.[js, min.js], and none of those two have the standard ES6 module export. 

I currently use Bower (which pulls from NPM) as my resource manager.

**Comment by gtrevg** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  gtrevg@gmail.com
    Domain plentyproductions.com has exceeded the max emails per hour (204/200 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:34924 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server21.abstractdns.com with esmtps (TLSv1:DHE-RSA-AES256-SHA:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bJ0DA-0008MD-MI
	for github@trevorgattis.com; Fri, 01 Jul 2016 15:18:32 +0000
Date: Wed, 29 Jun 2016 20:55:08 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1467258908;
	bh=nzLi6VEFhdvhMx5cCA2Gn2P7YPrTgTF7Zy1mlZBEhGs=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=jLunGVPSaSRIUEqz30dlKbBZqiA9wIV3AoCchJlRpUa7Ym9LiUwyQIwDSly+Vegk2
	 NPw1Bw3QNUq1BYgbgt7Vg3MxSEpH4VSV4QiE9bzPNtHVwxRtwW5NkLZFZWy60lQsvr
	 TWhmKobYsbgc/XQ9OTT5MgMw+PeF3lyc4jNm+IrU=

**Comment by rubennorte** [comment]
I think you should leave caching out of the Axios core, as it's usually complex (caching in memory does not scale in large applications, there isn't a standard interface for external caching services, etc.) and it can be implemented via interceptors.

Also, it looks like request cancellation is something that many libraries don't implement or don't document (I'm looking at you, `fetch` and `request`) and could be implemented later, after there is some consensus about what's the approach to be used.

What do you think?

**Comment by mzabriskie** [comment]
@rubennorte I tend to agree with you. I think if we knocked out #48 and #107 as well as any outstanding bugs we could be okay on releasing a 1.0.

**Comment by mzabriskie** [comment]
@rubennorte actually I think #48 is a bit of low hanging fruit. It can be managed with interceptors, just like caching, and it doesn't seem to be highly requested. I think if we add some examples to the [Cookbook](https://github.com/mzabriskie/axios/blob/master/COOKBOOK.md) for these use cases we can leave it out of the core. Thoughts?

**Comment by rubennorte** [comment]
I think #48 should be implemented in a plugin instead of inside Axios. Something that would be used like:

```javascript
var axios = require('axios');
var axiosCookie = require('axios-tough-cookie');

axiosCookie(axios, options);

// Or
var instance = axios.create(...);
axiosCookie(instance, options);
```

It's very similar to one I made for request retries (I'll open source it soon) and it was very easy to create and use.

What we could define are some guidelines for plugin creation. Maybe a naming recommendation (axios-foo or axios-plugin-foo) or specific keywords in the package.json so they are easy to find (and list them here). Also we could use the plugin community to detect features that are very frequently used and add them to the core.

**Comment by rubennorte** [comment]
@mzabriskie #107 I agree we should probably support it in the core.

Also I considered that this could be done via an internal interceptor until I realized that it must be implemented in the http adapter (because it need to manipulate the parsed URL). Do you think we should consider that approach for the cases that allow it?

**Comment by Treri** [comment]
> @FarhadG I built a module for caching that I had considered using for this, but I am not married to that. It would be nice to allow whatever is used to be pluggable, so people can provide their own cache mechanism if they want.

I like angular's set cache config style when perform a request. And I split out angular's $cacheFactory to do it.

And as long as we define a  cache Interface, like required method `put`, `get`, `remove`, `removeAll` etc. then any cache implement can be used in our request.

**Comment by teppeis** [comment]
@mzabriskie #48 and #107 have been closed. Could you release v1.0.0?

**Comment by mpeyper** [comment]
@mzabriskie is there an ETA on when v1 might come about? Is there anything still outstanding?

**Comment by emilyemorehouse** [comment]
Closing this in favor of #1333.
The remaining open task from this list (Documentation #257) has also been included on the new issue.
